spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/s3test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false